### ISSUE TITLE
Cannot start IDEA plug-in from Eclipse

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-idea#11]
Steps to reproduce:
- Setup a new Xtext language with IDEA support in Eclipse
- Run `gradle runIdea`
  -> The plug-in is not installed and not available in the spawned IDEA IDE

**Comment by suzel** [comment]
some problem

`0    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - [XtextLinkingDiagnostic: null:15 Couldn't resolve reference to JvmIdentifiableElement 'ideaPlugin'., XtextLinkingDiagnostic: null:16 Couldn't resolve reference to JvmIdentifiableElement 'enabled'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:15 Couldn't resolve reference to JvmIdentifiableElement 'ideaPlugin'., XtextLinkingDiagnostic: null:16 Couldn't resolve reference to JvmIdentifiableElement 'enabled'.]
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:88)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
:com.suzel.dsl.mydsl:generateXtextLanguage FAILED`

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
