### ISSUE TITLE
[build] Failure with plugin org.xtext.xtend

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-idea#33]
The build of xtext-idea fails with the error message:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/thoms/temp/xtext-idea/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'xtext-idea'.
> Failed to apply plugin [class 'org.xtext.gradle.XtextBuilderPlugin']
   > Could not create an instance of type org.xtext.gradle.tasks.XtextExtension_Decorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by kthoms** [comment]
Log with stacktrace:
[xtext-idea-33.txt](https://github.com/eclipse/xtext-idea/files/701573/xtext-idea-33.txt)

```
> Failed to apply plugin [class 'org.xtext.gradle.XtextBuilderPlugin']
   > Could not create an instance of type org.xtext.gradle.tasks.XtextExtension_Decorated.
[...]
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at org.xtext.gradle.tasks.XtextExtension.<init>(XtextExtension.java:64)
        at org.xtext.gradle.tasks.XtextExtension_Decorated.<init>(Unknown Source)
```

**Comment by spoenemann** [comment]
@oehme is there already an xtext-gradle-plugin issue for this?

**Comment by spoenemann** [comment]
Ah I see: xtext/xtext-gradle-plugin#74

**Comment by kthoms** [comment]
It was a broken Gradle cache.
