### ISSUE TITLE
FileTooBigException

### ISSUE THREAD

**Issue by ArchCC** [eclipse/xtext-idea#43]
After update to idea 2017.1 has this trouble on big project with enabled xtext plugin support

2017-03-24 14:32:46,001 [14700186]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.lang.RuntimeException: com.intellij.openapi.util.io.FileTooBigException: <path_to_workspace>/.idea/xtextAutoBuilderState.xml
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:176)
	at com.intellij.util.lang.CompoundRuntimeException.throwIfNotEmpty(CompoundRuntimeException.java:148)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:200)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:352)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:137)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:125)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.a(SaveAndSyncHandlerImpl.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:84)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2.a(FrameStateManagerImpl.java:70)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:418)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:343)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:385)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.openapi.util.io.FileTooBigException: <path_to_workspace>/.idea/xtextAutoBuilderState.xml
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.a(VirtualFileImpl.java:182)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getOutputStream(VirtualFileImpl.java:133)
	at com.intellij.openapi.vfs.VirtualFile.getOutputStream(VirtualFile.java:585)
	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1$1.compute(actions.kt:58)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1035)
	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$1.run(actions.kt:29)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:323)
	at com.intellij.configurationStore.FileBasedStorageKt.a(FileBasedStorage.kt:307)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:209)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:102)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession.save(XmlElementStorage.kt:140)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.save(FileBasedStorage.kt:87)
	at com.intellij.configurationStore.ComponentStoreImplKt.executeSave(ComponentStoreImpl.kt:489)
	at com.intellij.configurationStore.ComponentStoreImpl.doSave(ComponentStoreImpl.kt:241)
	at com.intellij.configurationStore.ProjectStoreImpl.doSave(ProjectStoreImpl.kt:350)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:198)
	... 37 more

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
