### ISSUE TITLE
Xtext IDEA plugin prevents breakpoint debugging in all projects while enabled

### ISSUE THREAD

**Issue by tommyettinger** [eclipse/xtext-idea#6]
Problem: When I try to debug a Maven project (which does not depend on XText) using breakpoints and the normal debug configuration for a `main()` method in IntelliJ IDEA, a notification pops up that an internal IDE error has occured, and all breakpoints are ignored (as if I had run the project, instead of debugged it).

Installation status: I am running IntelliJ 2016.2 on Windows 7, 64-bit, with Java 8 (OpenJDK, a Zulu build). I have the XText, XTend, and XText IDEA Core plugins enabled (version 2.11.0-SNAPSHOT, though I don't know how to check exactly what snapshot version), as well as some others (mostly supplied with IDEA, but also a Lombok plugin and Cursive for Clojure support, neither of which are currently in use in the project). My project is a [multi-module Maven project](https://github.com/SquidPony/SquidLib) and I generally run examples to check features using a main method instead of with JUnit, though I do sometimes use JUnit.

Steps to cause:
  1) Set a breakpoint where it should be executed by the program during debugging.
  2) Click the "bug" icon for debugging next to the run icon and run configuration dropdown.
  3) Note internal error attributed to XText:

```
Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


java.lang.Error: Unresolved compilation problems:
Access restriction: The type AbsentInformationException is not accessible due to restriction on required project org.eclipse.xtext.idea
    at org.eclipse.xtext.idea.debug.TraceBasedPositionManagerFactory$TraceBasedPositionManager.createPrepareRequest(TraceBasedPositionManagerFactory.java:68)
    at com.intellij.debugger.engine.CompoundPositionManager.lambda$createPrepareRequests$4(CompoundPositionManager.java:148)
    at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
    at com.intellij.debugger.engine.CompoundPositionManager.createPrepareRequests(CompoundPositionManager.java:143)
    at com.intellij.debugger.engine.requests.RequestManagerImpl.callbackOnPrepareClasses(RequestManagerImpl.java:308)
    at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:196)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:276)
    at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

(That might have been the same error repeated more than once, I'm not exactly sure how much was output each time I ran.)

Steps to partially resolve: Disable the XText, XTend, and XText IDEA Core plugins. Obviously this is not ideal, since it makes using XText not easy.

Are there any possible solutions for this?

**Comment by tommyettinger** [comment]
Are the issues on GitHub not the right venue for discussing indefinite-hiatus-causing bugs? Maybe some nice chitchat would help get everyone ready to discuss the issue. @svenefftinge , our last names sound very similar! And I think we both have used Java so much that we're fed up with certain problems and want something better out there. @spoenemann , our last names do not sound similar! But you committed some nice build quality stuff 15 days ago; thanks for that!

So does anyone have any ideas on how I can resolve this bug that affects debugging in every project while the XText family of IDEA plugins are enabled?

**Comment by fawind** [comment]
Any updates here?

**Comment by spoenemann** [comment]
"Unresolved compilation problems" sounds like a problem in our new restructured repository. I'll try to verify that soon.

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix

**Comment by tommyettinger** [comment]
For anyone still reading this, I'm looking into [Manifold](http://manifold.systems/), which does some similar things to Xtend in some ways, but is built around adding features to Java rather than making a new language entirely. It has an IDEA and Android Studio plugin, but not an Eclipse one. Hooray, platform fragmentation!
